### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by TGuillerme** [TGuillerme/moms#1]
# Moms: the shiny app
- [x] Do the moms user vignette
- [x] Add the extra ecology metrics to the app (and dispRity!)

# Shifting spaces: the paper
- [x] Discussion section
- [x] Extra gmm data
- [x] Extra ecology data
